study_registration/budgets/urls.py
from django.urls import path

from .views import BudgetApproveView
from .views import BudgetCreateView
from .views import BudgetDeleteView
from .views import BudgetUpdateView

app_name = 'budgets'
urlpatterns = [
    path('new/', BudgetCreateView.as_view(), name='create'),
    path('<int:pk>/update/', BudgetUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', BudgetDeleteView.as_view(), name='delete'),
    path('<int:pk>/approve/', BudgetApproveView.as_view(), name='approve'),
]

study_registration/urls.py
from bootstrap_colors.views import BootstrapColorsView
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from study_registration.budgets.views import BudgetListView
from study_registration.deployments.api import DeploymentsApiView
from study_registration.deployments.views import DeploymentListView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='studies:list'), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path(
        'contact/', TemplateView.as_view(template_name='contact.html'), name='contact'
    ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('colors.css', cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ), name='colors'),
    path(
        'studies/<int:study_pk>-<slug:study_short>/publications/',
        include('study_registration.publications.urls', namespace='publications'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/datasets/',
        include('study_registration.datasets.urls', namespace='datasets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/budgets/',
        include('study_registration.budgets.urls', namespace='budgets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/deployments/',
        include('study_registration.deployments.urls', namespace='deployments'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/biosamples/',
        include('study_registration.biosamples.urls', namespace='biosamples'),
    ),
    path('studies/', include('study_registration.studies.urls', namespace='studies')),
    path('budgets/', BudgetListView.as_view(), name='budget-list'),
    path('deployments/', DeploymentListView.as_view(), name='deployment-list'),
    path('api/deployments/', DeploymentsApiView.as_view(), name='deployment-api'),
]

try:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

study_registration/budgets/models.py
from django.conf import settings
from django.db import models
from django.utils.translation import gettext_lazy as _

from study_registration.studies.models import Study


class Budget(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE, verbose_name=_('Study'))
    expected = models.DecimalField(
        _('Expected cost (€)'), max_digits=12, decimal_places=2
    )
    actual = models.DecimalField(
        _('Actual cost (€)'), max_digits=12, decimal_places=2, blank=True, null=True
    )

    motivation = models.TextField(_('Motivation'), help_text=_(
        'Please provide additional information about the planned study. '
        'What we would like to know is why you need to run the study '
        'and why there is no less expensive route. '
        "The document should contain sections on the study's "
        'theoretical background and motivation, '
        'research question and implications for the literature, '
        'design of the study, '
        'anticipated deliverables, '
        'and the timeline.'
    ), blank=True)

    approved_by = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Approved by'),
        on_delete=models.PROTECT,
        related_name='+',
        blank=True,
        null=True,
    )

    class Meta:
        permissions = [
            ('approve', _('Can approve')),
        ]

    def needs_approval(self):
        return self.expected >= settings.BUDGETS_APPROVAL_THRESHOLD

study_registration/budgets/forms.py
from django import forms
from django.conf import settings
from django.core.exceptions import ValidationError

from .models import Budget


class BudgetForm(forms.ModelForm):
    class Meta:
        model = Budget
        fields = [
            'expected',
            'actual',
            'motivation',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.threshold = settings.BUDGETS_APPROVAL_THRESHOLD

    def clean(self):
        cleaned_data = super().clean()

        if cleaned_data.get('expected', 0) >= self.threshold:
            motivation_field = self.fields['motivation']
            if not cleaned_data.get('motivation'):
                err = ValidationError(
                    motivation_field.error_messages['required'], code='required'
                )
                self.add_error('motivation', err)

        return cleaned_data

study_registration/budgets/views.py
from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from study_registration.studies.mixins import StudyAspectMixin
from study_registration.users.models import User
from study_registration.utils.mail import send_mail
from study_registration.utils.mail import send_study_mail

from .forms import BudgetForm
from .models import Budget


class BudgetCreateView(StudyAspectMixin, CreateView):
    model = Budget
    form_class = BudgetForm
    ethics_required = True

    def send_notification(self):
        to = (
            User.objects
            .with_perm('budgets.approve', include_superusers=False)
            .exclude(email=None)
            .exclude(is_active=False)
            .values_list('email', flat=True)
        )

        user = self.request.user.get_full_name()
        threshold = settings.BUDGETS_APPROVAL_THRESHOLD
        link = self.request.build_absolute_uri(
            reverse(
                'budgets:approve',
                args=[self.study.pk, self.study.short_title, self.object.pk],
            )
        )

        subject = settings.EMAIL_SUBJECT_PREFIX + 'Budget approval requested'
        body = (
            f'{user} registered a study budget over {threshold}\xa0€. '
            f'They are asking for your approval:\n\n{link}'
        )

        return send_mail(subject, body, None, to)

    def form_valid(self, form):
        form.instance.study = self.study
        self.object = form.save()
        self.send_notification()
        return redirect(self.get_success_url())


class BudgetUpdateView(StudyAspectMixin, UpdateView):
    model = Budget
    form_class = BudgetForm


class BudgetDeleteView(StudyAspectMixin, DeleteView):
    model = Budget


class ApproverRequiredMixin(PermissionRequiredMixin):
    permission_required = ['budgets.approve']

    def get_queryset(self):
        return (
            super().get_queryset()
            .filter(expected__gte=settings.BUDGETS_APPROVAL_THRESHOLD)
            .order_by('-pk')
        )


class BudgetListView(ApproverRequiredMixin, ListView):
    model = Budget
    paginate_by = 20
    ordering = ['-pk']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filters'] = [
            ('', _('All')),
            ('approved', _('Approved')),
            ('not-approved', _('Not approved')),
        ]
        return context

    def get_queryset(self):
        qs = super().get_queryset().select_related(
            'study__contact_person',
            'approved_by',
        )
        if self.request.GET.get('filter') == 'approved':
            return qs.exclude(approved_by=None)
        elif self.request.GET.get('filter') == 'not-approved':
            return qs.filter(approved_by=None)
        else:
            return qs


class BudgetApproveView(ApproverRequiredMixin, StudyAspectMixin, DetailView):
    model = Budget
    template_name_suffix = '_approve'
    owner_required = False

    def send_notification(self):
        user = self.request.user.get_full_name()
        study = self.study.title
        if self.object.approved_by:
            body = f'A budget for your study "{study}" got approved by {user}.'
        else:
            body = f'A budget for Your study "{study}" got declined by {user}.'

        return send_study_mail('Study approval changed', body, self.study, self.request)

    def post(self, request, **kwargs):
        self.object = self.get_object()

        if self.request.POST.get('approved'):
            self.object.approved_by = request.user
        else:
            self.object.approved_by = None
        self.object.save()

        self.send_notification()
        return redirect(request.path)

study_registration/budgets/templates/budgets/_study_detail_budgets.html
{% load i18n utils %}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h2 class="m-0">{% translate 'Budgets' %}</h2>
        {% if is_owner and study.ethics_confirmed %}
            <div class="d-print-none flex-shrink-0 ms-1">
                <a href="{% url 'budgets:create' study.pk study.short_title %}" class="btn btn-sm btn-primary">{% translate 'Add budget' %}</a>
            </div>
        {% endif %}
    </div>
    <div class="card-body">
        {% for budget in study.budget_set.all %}
            {% if is_owner %}
                <div class="d-print-none float-end ms-1 mb-1">
                    <a href="{% url 'budgets:update' study.pk study.short_title budget.pk %}" class="btn btn-sm btn-outline-primary">{% translate 'Update' %}</a>
                    <a href="{% url 'budgets:delete' study.pk study.short_title budget.pk %}" class="btn btn-sm btn-outline-danger">{% translate 'Delete' %}</a>
                </div>
            {% endif %}
            {% if budget.needs_approval %}
                {% if perms.budgets.approve %}
                    <div class="d-print-none float-end ms-1 mb-1">
                        <a href="{% url 'budgets:approve' study.pk study.short_title budget.pk %}" class="btn btn-sm btn-outline-primary">{% translate 'Approve' %}</a>
                    </div>
                {% endif %}
            {% endif %}
            {{ budget.expected }}&nbsp;€
            {% if budget.actual %}
                ({{ budget.actual }}&nbsp;€)
            {% endif %}
            {% if budget.approved_by %}
                <span class="badge text-bg-success">{% translate 'approved' %}</span>
            {% endif %}
            {% if not forloop.last %}<hr>{% endif %}
        {% empty %}
            {% if study.ethics_confirmed %}
                <div class="d-block alert alert-warning">{% translate 'No budgets so far' %}</div>
            {% else %}
                <div class="d-block alert alert-danger">{% translate 'Ethics approval required' %}</div>
            {% endif %}
        {% endfor %}
    </div>
</div>

study_registration/budgets/templates/budgets/budget_approve.html
{% extends "budgets/budget_base.html" %}
{% load i18n django_bootstrap5 utils %}

{% block content %}
    <div class="card mb-4">
        <div class="card-body">
            <h2 class="card-title">{{ study.title }}</h2>
            {% icon 'user' %} {{ budget.study.contact_person.get_full_name }}
            &middot; {{ study.created_at }}
            &middot; {{ budget.expected|floatformat:2 }}&nbsp;&euro;
            {% if budget.approved_by %}
                &middot; <span class="badge text-bg-success">{% translate 'approved' %}</span>
            {% endif %}
        </div>
    </div>

    {{ object.motivation|urlize|linebreaks }}

    <form class="d-print-none mb-3" method="post">
        {% csrf_token %}
        {% if object.approved_by %}
            <button class="btn btn-danger" name="approved" value="">{% translate 'Withdraw approval' %}</button>
        {% else %}
            <button class="btn btn-primary" name="approved" value="1">{% translate 'Approve' %}</button>
        {% endif %}
    </form>
{% endblock %}

study_registration/budgets/templates/budgets/budget_base.html
{% extends "studies/study_base.html" %}
{% load i18n %}

{% block title %}
    {% if budget %}
        {% translate "Budget" %}
    {% else %}
        {% translate "Add Budget" %}
    {% endif %}
    &middot; {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if budget %}
        <li class="breadcrumb-item"><a href="{% url 'budgets:update' study.pk study.short_title budget.pk %}">{% translate 'Budget' %}</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'budgets:create' study.pk study.short_title %}">{% translate 'Add budget' %}</a></li>
    {% endif %}
{% endblock %}

study_registration/budgets/templates/budgets/budget_confirm_delete.html
{% extends "budgets/budget_base.html" %}
{% load i18n %}

{% block title %}{% translate 'Delete' %} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'budgets:delete' study.pk study.short_title budget.pk %}">{% translate 'Delete' %}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktranslate %}
                Are you sure you want to <strong>permanently delete</strong> this budget?
            {% endblocktranslate %}
        </p>
        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

study_registration/budgets/templates/budgets/budget_form.html
{% extends "budgets/budget_base.html" %}
{% load i18n static django_bootstrap5 %}

{% block content %}
    <form method="post">
        {% include 'form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.expected %}
        {% bootstrap_field form.actual %}
        <div data-threshold="{{ form.threshold }}">
            {% bootstrap_field form.motivation %}
        </div>

        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

{% block extra_scripts %}
    <script type="module" src="{% static 'budget-form.js' %}"></script>
{% endblock %}

study_registration/budgets/templates/budgets/budget_list.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 utils %}

{% block title %}{% translate 'Budgets' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <nav aria-label="{% translate 'List' %}" class="mb-3">
        <ul class="nav nav-pills justify-content-center mb-3">
            {% for value, label in filters %}
                <li class="nav-item">
                    <a class="nav-link {% if request.GET.filter|default:'' == value %}active{% endif %}" href="?filter={{ value }}">{{ label }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>

    <ul class="p-0">
        {% for budget in object_list %}
            <li class="card mb-2">
                <div class="card-body">
                    <h2 class="card-title"><a href="{% url 'budgets:approve' budget.study.pk budget.study.short_title budget.pk %}" class="link-lite">{{ budget.study.title }}</a></h2>
                    {% icon 'user' %} {{ budget.study.contact_person.get_full_name }}
                    &middot; {{ budget.study.created_at }}
                    &middot; {{ budget.expected|floatformat:2 }}&nbsp;&euro;
                    {% if budget.approved_by %}
                        &middot; <span class="badge text-bg-success">{% translate 'approved' %}</span>
                    {% endif %}
                </div>
            </li>
        {% empty %}
            <li class="d-block alert alert-warning">
                {% translate 'No budgets that need approval' %}
            </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="{% translate 'Pagination' %}">
            {% bootstrap_pagination page_obj url=request.get_full_path %}
        </nav>
    {% endif %}
{% endblock %}