study_registration/deployments/urls.py
from django.urls import path

from .api import GitlabCommitsApiView
from .api import GitlabFilesApiView
from .api import GitlabProjectApiView
from .views import DeploymentCreateView
from .views import DeploymentDeleteView
from .views import DeploymentDeployView
from .views import DeploymentRedeployView
from .views import DeploymentUpdateView

app_name = 'deployments'
urlpatterns = [
    path('new/', DeploymentCreateView.as_view(), name='create'),
    path('<int:pk>/update/', DeploymentUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', DeploymentDeleteView.as_view(), name='delete'),
    path('<int:pk>/redeploy/', DeploymentRedeployView.as_view(), name='redeploy'),
    path('<int:pk>/deploy/', DeploymentDeployView.as_view(), name='deploy'),
    path('gitlab/project/', GitlabProjectApiView.as_view(), name='gitlab-project'),
    path('gitlab/commits/', GitlabCommitsApiView.as_view(), name='gitlab-commits'),
    path('gitlab/files/', GitlabFilesApiView.as_view(), name='gitlab-files'),
]

study_registration/urls.py
from bootstrap_colors.views import BootstrapColorsView
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from study_registration.budgets.views import BudgetListView
from study_registration.deployments.api import DeploymentsApiView
from study_registration.deployments.views import DeploymentListView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='studies:list'), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path(
        'contact/', TemplateView.as_view(template_name='contact.html'), name='contact'
    ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('colors.css', cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ), name='colors'),
    path(
        'studies/<int:study_pk>-<slug:study_short>/publications/',
        include('study_registration.publications.urls', namespace='publications'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/datasets/',
        include('study_registration.datasets.urls', namespace='datasets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/budgets/',
        include('study_registration.budgets.urls', namespace='budgets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/deployments/',
        include('study_registration.deployments.urls', namespace='deployments'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/biosamples/',
        include('study_registration.biosamples.urls', namespace='biosamples'),
    ),
    path('studies/', include('study_registration.studies.urls', namespace='studies')),
    path('budgets/', BudgetListView.as_view(), name='budget-list'),
    path('deployments/', DeploymentListView.as_view(), name='deployment-list'),
    path('api/deployments/', DeploymentsApiView.as_view(), name='deployment-api'),
]

try:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

study_registration/deployments/models.py
import datetime

from django.db import models
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from study_registration.studies.models import Department
from study_registration.studies.models import Study
from study_registration.utils.fields import DateField


class DeployTarget(models.Model):
    name = models.CharField(_('Name'), max_length=256, unique=True)
    key = models.SlugField(_('key'), max_length=32, unique=True)
    departments = models.ManyToManyField(
        Department,
        verbose_name=_('Departments that can use this target'),
    )
    ethics_required = models.BooleanField(_('Ethics required'), default=True)
    gitlab_deploy_key = models.PositiveIntegerField(
        _('GitLab deploy key'), blank=True, null=True
    )
    url_template = models.CharField(
        _('Target URL template'), max_length=256, blank=True
    )

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class BaseDeployment(models.Model):
    class Meta:
        abstract = True

    created_at = models.DateField(_('Created at'), auto_now_add=True)
    git_ref = models.CharField(_('Branch'), max_length=64, default='main')
    git_file = models.CharField(
        _('Name of the file within the repository that starts your experiment'),
        help_text=_(
            'A desktop shortcut to this file will be created on the '
            'laboratory computers.'
        ),
        max_length=256,
    )
    commit_sha = models.CharField(_('Commit (version)'), max_length=50)
    startdate = DateField(_('Start of deployment'))
    enddate = DateField(
        _('End of deployment'),
        help_text=_(
            'Your files and collected data will automatically be deleted '
            'from the deployment target after that date.'
        ),
    )


class Deployment(BaseDeployment):
    study = models.ForeignKey(Study, on_delete=models.CASCADE, verbose_name=_('Study'))
    legacy_study_id = models.CharField(_('Legacy study ID'), max_length=254, blank=True)
    legacy_branch = models.CharField(_('Legacy branch'), max_length=254, blank=True)

    git_repo = models.CharField(_('Repository URL'), max_length=256)
    gitlab_id = models.IntegerField(
        _('GitLab project ID'),
        help_text=_(
            'The project ID is displayed right below the project title on GitLab.'
        ),
    )
    target = models.ForeignKey(
        DeployTarget, verbose_name=_('Deploy target'), on_delete=models.PROTECT
    )
    targeturl = models.CharField(_('Target URL'), max_length=300, blank=True)
    rejected = models.BooleanField(_('Rejected'), default=False)
    end_reminded = models.BooleanField(default=False)

    class Meta:
        permissions = [
            ('approve', _('Can approve')),
        ]

    def __str__(self):
        return '{} {} {}'.format(
            self.git_repo.split('/')[-1],
            self.git_ref,
            self.git_file,
        )

    @property
    def deployment_id(self):
        return self.legacy_study_id or f'{self.study}-{self.id}'

    @property
    def generated_branch(self):
        return self.legacy_branch or f'deployment-{self.id}'

    def create_revision(self):
        self.revisions.create(
            deployment=self,
            git_ref=self.git_ref,
            git_file=self.git_file,
            commit_sha=self.commit_sha,
            startdate=self.startdate,
            enddate=self.enddate,
        )

    @cached_property
    def deployed(self):
        return self.revisions.exists()

    @property
    def expired(self):
        return self.enddate < datetime.date.today()

    @property
    def status(self):
        if self.rejected:
            return _('rejected')
        elif not self.deployed:
            return _('not running')
        elif self.expired:
            return _('expired')
        else:
            return _('running')

    @property
    def status_color(self):
        if self.rejected:
            return 'danger'
        elif not self.deployed:
            return 'danger'
        elif self.expired:
            return 'danger'
        else:
            return 'success'


class DeploymentRevision(BaseDeployment):
    deployment = models.ForeignKey(
        Deployment, on_delete=models.CASCADE, related_name='revisions'
    )

study_registration/deployments/forms.py
import datetime

from django import forms
from django.conf import settings
from django.core.validators import MaxValueValidator
from django.utils.translation import gettext_lazy as _

from .models import Deployment


class DeploymentForm(forms.ModelForm):
    class Meta:
        model = Deployment
        fields = [
            'git_repo',
            'git_ref',
            'git_file',
            'gitlab_id',
            'commit_sha',
            'target',
            'startdate',
            'enddate',
        ]

    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.fields['startdate'].initial = datetime.date.today()
        self.fields['enddate'].validators.append(
            MaxValueValidator(limit_value=(
                datetime.date.today() + settings.DEPLOYMENTS_DURATION_MAX
            ))
        )

    def clean(self):
        cleaned_data = super().clean()
        startdate = cleaned_data.get('startdate')
        enddate = cleaned_data.get('enddate')

        if startdate and enddate and enddate <= startdate:
            self.add_error(
                'enddate',
                _('The deployment cannot end before it has even started')
            )

study_registration/deployments/views.py
import datetime

from django.conf import settings
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.core.exceptions import SuspiciousOperation
from django.shortcuts import get_object_or_404
from django.shortcuts import redirect
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import DetailView
from django.views.generic import ListView
from django.views.generic import UpdateView

from study_registration.studies.mixins import StudyAspectMixin
from study_registration.users.models import User
from study_registration.utils.mail import send_mail
from study_registration.utils.mail import send_study_mail

from . import gitlab
from .forms import DeploymentForm
from .models import Deployment


class DeploymentFormMixin(StudyAspectMixin):
    model = Deployment
    form_class = DeploymentForm

    def get_form(self, **kwargs):
        form = super().get_form(**kwargs)
        form.fields['target'].queryset = self.study.department.deploytarget_set.all()
        if not self.study.ethics_confirmed:
            form.fields['target'].queryset = (
                form.fields['target'].queryset.filter(ethics_required=False)
            )
        return form

    def form_valid(self, form):
        if not self.request.user.is_superuser:
            gitlab_id = form.cleaned_data['gitlab_id']
            if not gitlab.is_project_member(gitlab_id, self.request.user.username):
                raise SuspiciousOperation
        return super().form_valid(form)


class DeploymentCreateView(DeploymentFormMixin, CreateView):
    def send_notification(self):
        to = (
            User.objects
            .with_perm('deployments.approve', include_superusers=False)
            .exclude(email=None)
            .exclude(is_active=False)
            .values_list('email', flat=True)
        )

        subject = settings.EMAIL_SUBJECT_PREFIX + 'Deployment request'

        user = self.request.user.get_full_name()
        study = self.study.title
        link = self.request.build_absolute_uri(
            reverse('deployments:deploy', args=[
                self.study.pk, self.study.short_title, self.object.pk
            ])
        )
        body = (
            f'Your researcher {user} wants to publish their study "{study}"\n\n'
            f'View details here: {link}'
        )

        return send_mail(subject, body, None, to)

    def form_valid(self, form):
        form.instance.study = self.study
        response = super().form_valid(form)
        self.send_notification()
        return response


class DeploymentUpdateView(DeploymentFormMixin, UpdateView):
    def get_object(self):
        return get_object_or_404(
            super().get_queryset().filter(revisions=None),
            pk=self.kwargs['pk'],
        )


class DeploymentDeleteView(StudyAspectMixin, DeleteView):
    model = Deployment

    def get_object(self):
        return get_object_or_404(
            super().get_queryset().filter(revisions=None),
            pk=self.kwargs['pk'],
        )


class DeploymentListView(PermissionRequiredMixin, ListView):
    model = Deployment
    permission_required = ['deployments.approve']
    ordering = ['-pk']
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filters'] = [
            ('', _('All')),
            ('not-running', _('Not running')),
            ('running', _('Running')),
            ('expired', _('Expired')),
            ('rejected', _('Rejected')),
        ]
        return context

    def get_queryset(self):
        qs = super().get_queryset().select_related(
            'study__contact_person',
            'target',
        )
        today = datetime.date.today()
        if self.request.GET.get('filter') == 'rejected':
            return qs.filter(rejected=True)
        elif self.request.GET.get('filter') == 'not-running':
            return qs.filter(revisions=None, rejected=False)
        elif self.request.GET.get('filter') == 'running':
            return qs.exclude(revisions=None).filter(enddate__gte=today, rejected=False)
        elif self.request.GET.get('filter') == 'expired':
            return qs.exclude(revisions=None).filter(enddate__lt=today, rejected=False)
        else:
            return qs


class DeploymentRedeployView(StudyAspectMixin, UpdateView):
    model = Deployment
    template_name_suffix = '_redeploy'
    fields = [
        'git_ref',
        'git_file',
        'commit_sha',
        'startdate',
        'enddate',
    ]

    def get_object(self):
        return get_object_or_404(
            (
                super().get_queryset()
                .exclude(revisions=None)
                .exclude(enddate__lt=datetime.date.today())
            ),
            pk=self.kwargs['pk'],
        )

    def form_valid(self, form):
        form.instance.end_reminded = False
        response = super().form_valid(form)
        gitlab.create_deploy_branch(
            self.object.gitlab_id,
            self.object.generated_branch,
            self.object.commit_sha,
        )
        self.object.create_revision()
        return response


class DeploymentDeployView(PermissionRequiredMixin, StudyAspectMixin, DetailView):
    model = Deployment
    template_name_suffix = '_deploy'
    permission_required = ['deployments.approve']
    owner_required = False

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['default_target_url'] = (
            self.object.target.url_template
            .replace('{study_id}', str(self.study))
            .replace('{deployment_id}', self.object.deployment_id)
            .replace('{study_id:-}', str(self.study).replace('_', '-'))
            .replace('{deployment_id:-}', self.object.deployment_id.replace('_', '-'))
        )
        return context

    def send_notification(self):
        study = self.study.title
        targeturl = self.object.targeturl
        link = self.request.build_absolute_uri(
            reverse('deployments:redeploy', args=[
                self.study.pk, self.study.short_title, self.object.pk
            ])
        )
        body = (
            f'Your study "{study}" has been deployed to the laboratory computers. '
            f'Your experiment is located in the path: {targeturl}.\n'
            f'View details here: {link}'
        )
        if self.request.POST.get('mail_comment'):
            body += '\n\n' + self.request.POST['mail_comment']

        approvers = (
            User.objects
            .with_perm('deployments.approve', include_superusers=False)
            .exclude(email=None)
            .values_list('email', flat=True)
        )

        return send_study_mail(
            'Deployment request processed',
            body,
            self.study,
            self.request,
            additional_to=approvers,
        )

    def post(self, request, **kwargs):
        self.object = self.get_object()

        if request.POST.get('action') == 'deploy':
            if self.object.deployed:
                raise SuspiciousOperation

            gitlab.create_deploy_branch(
                self.object.gitlab_id,
                self.object.generated_branch,
                self.object.commit_sha,
            )
            if self.object.target.gitlab_deploy_key is not None:
                gitlab.enable_deploy_key(
                    self.object.gitlab_id,
                    self.object.target.gitlab_deploy_key
                )
            self.object.create_revision()
        elif request.POST.get('action') == 'targeturl':
            if self.object.targeturl or not request.POST.get('targeturl'):
                raise SuspiciousOperation

            self.object.targeturl = request.POST.get('targeturl')
            self.object.save()
            self.send_notification()
        elif request.POST.get('action') == 'reject':
            self.object.rejected = True
            self.object.save()
        elif request.POST.get('action') == 'restore':
            self.object.rejected = False
            self.object.save()

        return redirect(request.path)

study_registration/deployments/templates/deployments/_study_detail_deployments.html
{% load i18n utils %}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h2 class="m-0">{% translate 'Deployments' %}</h2>
        {% if is_owner %}
            <div class="d-print-none flex-shrink-0 ms-1">
                <a href="{% url 'deployments:create' study.pk study.short_title %}" class="btn btn-sm btn-primary">{% translate 'Add deployment' %}</a>
            </div>
        {% endif %}
    </div>
    <div class="card-body">
        {% for deployment in study.deployment_set.all %}
            <div class="d-print-none float-end ms-1 mb-1">
                {% if perms.deployments.approve %}
                    <a href="{% url 'deployments:deploy' study.pk study.short_title deployment.pk %}" class="btn btn-sm btn-outline-primary">
                        {% if deployment.deployed %}
                            {% translate 'Review' %}
                        {% else %}
                            {% translate 'Deploy' %}
                        {% endif %}
                    </a>
                {% endif %}
                {% if is_owner %}
                    {% if not deployment.deployed %}
                        <a href="{% url 'deployments:update' study.pk study.short_title deployment.pk %}" class="btn btn-sm btn-outline-primary">{% translate 'Update' %}</a>
                        <a href="{% url 'deployments:delete' study.pk study.short_title deployment.pk %}" class="btn btn-sm btn-outline-danger">{% translate 'Delete' %}</a>
                    {% elif not deployment.expired %}
                        <a href="{% url 'deployments:redeploy' study.pk study.short_title deployment.pk %}" class="btn btn-sm btn-outline-primary">{% translate 'Redeploy' %}</a>
                    {% endif %}
                {% endif %}
            </div>
            <dl>
                <dt>{% translate 'Status' %}</dt>
                <dd><span class="badge text-bg-{{ deployment.status_color }}">{{ deployment.status }}</span></dd>

                <dt>{{ deployment|verbose_name:'gitlab_id' }} / {{ deployment|verbose_name:'git_ref' }} / {% translate 'File' %}</dt>
                <dd>{{ deployment|display:'gitlab_id' }} / {{ deployment|display:'git_ref' }} / {{ deployment|display:'git_file' }}</dd>

                <dt>{{ deployment|verbose_name:'target' }}</dt>
                <dd><span class="badge text-bg-secondary">{{ deployment|display:'target' }}</span></dd>

                <dt>{% translate 'Deployment period' %}</dt>
                <dd>{{ deployment|display:'startdate' }} - {{ deployment|display:'enddate' }}</dd>
            </dl>
            {% if not forloop.last %}<hr>{% endif %}
        {% empty %}
            <div class="d-block alert alert-warning">{% translate 'No deployments so far' %}</div>
        {% endfor %}
    </div>
</div>

study_registration/deployments/templates/deployments/deployment_base.html
{% extends "studies/study_base.html" %}
{% load i18n %}

{% block title %}
    {% if deployment %}
        {% translate "Deployment" %}
    {% else %}
        {% translate "Add deployment" %}
    {% endif %}
    &middot; {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if deployment %}
        <li class="breadcrumb-item">{% translate 'Deployment' %}</li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'deployments:create' study.pk study.short_title %}">{% translate 'Add deployment' %}</a></li>
    {% endif %}
{% endblock %}

study_registration/deployments/templates/deployments/deployment_confirm_delete.html
{% extends "deployments/deployment_base.html" %}
{% load i18n %}

{% block title %}{% translate 'Delete' %} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'deployments:delete' study.pk study.short_title deployment.pk %}">{% translate 'Delete' %}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktranslate %}
                Are you sure you want to <strong>permanently delete</strong> this deployment?
            {% endblocktranslate %}
        </p>
        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

study_registration/deployments/templates/deployments/deployment_form.html
{% extends "deployments/deployment_base.html" %}
{% load i18n static django_bootstrap5 %}

{% block content %}
    <form method="post"
        data-gitlab-project="{% url 'deployments:gitlab-project' study.pk study.short_title %}"
        data-gitlab-commits="{% url 'deployments:gitlab-commits' study.pk study.short_title %}"
        data-gitlab-files="{% url 'deployments:gitlab-files' study.pk study.short_title %}">
        {% include 'form_errors.html' with form=form %}
        {% csrf_token %}

        <fieldset class="card mb-3">
            <div class="card-body">
                {% bootstrap_field form.gitlab_id %}
                <div class="mb-3">
                    <label class="form-label" for="{{ form.git_repo.id_for_label }}">{{ form.git_repo.label }}</label>
                    <input name="{{ form.git_repo.name }}" class="form-control-plaintext p-0" id="{{ form.git_repo.id_for_label }}" readonly placeholder="https://" tabindex="-1">
                </div>
                {% bootstrap_field form.git_ref %}
                {% bootstrap_field form.commit_sha %}
                {% bootstrap_field form.git_file %}
            </div>
        </fieldset>
        <div class="mb-3">
            {% bootstrap_field form.target wrapper_class='' %}
            {% if not study.ethics_confirmed %}
                <div class="form-text text-danger">
                    {% translate 'Ethics approval required to access more deploy targets' %}
                </div>
            {% endif %}
        </div>
        {% bootstrap_field form.startdate %}
        {% bootstrap_field form.enddate %}

        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'gitlab.js' %}" type="module"></script>
{% endblock %}

study_registration/deployments/templates/deployments/deployment_list.html
{% extends "base.html" %}
{% load i18n django_bootstrap5 utils %}

{% block title %}{% translate 'Deployments' %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <nav aria-label="{% translate 'List' %}" class="mb-3">
        <ul class="nav nav-pills justify-content-center mb-3">
            {% for value, label in filters %}
                <li class="nav-item">
                    <a class="nav-link {% if request.GET.filter|default:'' == value %}active{% endif %}" href="?filter={{ value }}">{{ label }}</a>
                </li>
            {% endfor %}
        </ul>
    </nav>

    <ul class="p-0">
        {% for deployment in object_list %}
            <li class="card mb-2">
                <div class="card-body">
                    <h2 class="card-title"><a href="{% url 'deployments:deploy' deployment.study.pk deployment.study.short_title deployment.pk %}" class="link-lite">{{ deployment.study.title }}</a></h2>
                    {% icon 'user' %} {{ deployment.study.contact_person.get_full_name }}
                    &middot; {{ deployment|display:'startdate' }} - {{ deployment|display:'enddate' }}
                    <span class="badge text-bg-secondary">{{ deployment|display:'target' }}</span>
                    <span class="badge text-bg-{{ deployment.status_color }}">{{ deployment.status }}</span>
                </div>
            </li>
        {% empty %}
            <li class="d-block alert alert-warning">
                {% translate 'No deployments' %}
            </li>
        {% endfor %}
    </ul>

    {% if is_paginated %}
        <nav aria-label="{% translate 'Pagination' %}">
            {% bootstrap_pagination page_obj url=request.get_full_path %}
        </nav>
    {% endif %}
{% endblock %}

study_registration/deployments/templates/deployments/deployment_redeploy.html
{% extends "deployments/deployment_base.html" %}
{% load i18n static django_bootstrap5 utils %}

{% block content %}
    <form method="post"
        data-gitlab-project="{% url 'deployments:gitlab-project' study.pk study.short_title %}"
        data-gitlab-commits="{% url 'deployments:gitlab-commits' study.pk study.short_title %}"
        data-gitlab-files="{% url 'deployments:gitlab-files' study.pk study.short_title %}">
        {% include 'form_errors.html' with form=form %}
        {% csrf_token %}

        <fieldset class="card mb-3">
            <div class="card-body">
                <div class="mb-3">
                    <label class="form-label" for="id_gitlab_id">{{ object|verbose_name:'gitlab_id' }}</label>
                    <input type="number" value="{{ object.gitlab_id }}" class="form-control" id="id_gitlab_id" disabled>
                </div>
                <div class="mb-3">
                    <label class="form-label" for="id_git_repo">{{ object|verbose_name:'git_repo' }}</label>
                    <input value="{{ object.git_repo }}" class="form-control-plaintext p-0" id="id_git_repo" disabled>
                </div>
                {% bootstrap_field form.git_ref %}
                {% bootstrap_field form.commit_sha %}
                {% bootstrap_field form.git_file %}
            </div>
        </fieldset>
        <div class="mb-3">
            <label class="form-label" for="id_target">{{ object|verbose_name:'target' }}</label>
            <select class="form-select" id="id_target" disabled>
                <option>{{ object.target }}</option>
            </select>
        </div>
        {% bootstrap_field form.startdate %}
        {% bootstrap_field form.enddate %}

        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Redeploy' %}</button>
        </div>
    </form>
{% endblock %}

{% block extra_scripts %}
    <script src="{% static 'gitlab.js' %}" type="module"></script>
{% endblock %}