study_registration/publications/urls.py
from django.urls import path

from .views import PublicationCreateView
from .views import PublicationDeleteView
from .views import PublicationUpdateView

app_name = 'publications'
urlpatterns = [
    path('new/', PublicationCreateView.as_view(), name='create'),
    path('<int:pk>/update/', PublicationUpdateView.as_view(), name='update'),
    path('<int:pk>/delete/', PublicationDeleteView.as_view(), name='delete'),
]

study_registration/urls.py
from bootstrap_colors.views import BootstrapColorsView
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from study_registration.budgets.views import BudgetListView
from study_registration.deployments.api import DeploymentsApiView
from study_registration.deployments.views import DeploymentListView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='studies:list'), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path(
        'contact/', TemplateView.as_view(template_name='contact.html'), name='contact'
    ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('colors.css', cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ), name='colors'),
    path(
        'studies/<int:study_pk>-<slug:study_short>/publications/',
        include('study_registration.publications.urls', namespace='publications'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/datasets/',
        include('study_registration.datasets.urls', namespace='datasets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/budgets/',
        include('study_registration.budgets.urls', namespace='budgets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/deployments/',
        include('study_registration.deployments.urls', namespace='deployments'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/biosamples/',
        include('study_registration.biosamples.urls', namespace='biosamples'),
    ),
    path('studies/', include('study_registration.studies.urls', namespace='studies')),
    path('budgets/', BudgetListView.as_view(), name='budget-list'),
    path('deployments/', DeploymentListView.as_view(), name='deployment-list'),
    path('api/deployments/', DeploymentsApiView.as_view(), name='deployment-api'),
]

try:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

study_registration/publications/models.py
from django.db import models
from django.utils.translation import gettext
from django.utils.translation import gettext_lazy as _

from study_registration.studies.models import Study


class Publication(models.Model):
    study = models.ForeignKey(Study, verbose_name=_('Study'), on_delete=models.CASCADE)
    doi = models.CharField(_('DOI'), max_length=254, blank=True, null=True, unique=True)
    title = models.CharField(_('Title'), max_length=254)
    authors = models.CharField(_('Authors'), max_length=254)
    journal = models.CharField(_('Journal'), max_length=254, blank=True)
    year = models.IntegerField(
        _('Year'),
        help_text=_(
            'When adding a publication, please remember '
            'to update "to be stored until" for the data folder.'
        ),
    )

    def __str__(self):
        return self.doi or gettext('Publication')

    def doi_url(self):
        return 'https://doi.org/' + self.doi

    def text(self):
        base = f'{self.authors} ({self.year}). {self.title}.'
        if self.journal:
            base += f' {self.journal}.'
        if self.doi:
            base += f' {self.doi_url()}'
        return base

study_registration/publications/forms.py
from django import forms
from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

from .models import Publication


class PublicationForm(forms.ModelForm):
    class Meta:
        model = Publication
        fields = ['doi', 'title', 'authors', 'journal', 'year']

    def clean_doi(self):
        value = self.cleaned_data['doi']

        if not value:
            return value

        value = value.removeprefix('doi:')
        value = value.removeprefix('https://doi.org/')

        if not value.startswith('10.'):
            raise ValidationError(_('DOI must start with 10.'))

        return value

study_registration/publications/views.py
from django.conf import settings
from django.views.generic import CreateView
from django.views.generic import DeleteView
from django.views.generic import UpdateView

from study_registration.studies.mixins import StudyAspectMixin
from study_registration.utils.mail import send_study_mail

from .forms import PublicationForm
from .models import Publication


class PublicationCreateView(StudyAspectMixin, CreateView):
    model = Publication
    form_class = PublicationForm

    def send_notification(self):
        text = self.object.text()
        user = self.request.user.get_full_name()
        study = self.study.title
        link = self.request.build_absolute_uri(self.study.get_absolute_url())

        body = (
            f'{user} added the following publication to the study '
            f'"{study}" ({link}):\n\n'
            f'  {text}\n\n'
            'This notification was also sent to the Research Data & Information, '
            'who will add the publication to the MPS publication repository '
            'https://pure.mpg.de.'
        )

        return send_study_mail(
            'New publication',
            body,
            self.study,
            self.request,
            additional_to=settings.PUBLICATION_NOTIFICATIONS_TO,
        )

    def form_valid(self, form):
        form.instance.study = self.study
        response = super().form_valid(form)
        self.send_notification()
        return response


class PublicationUpdateView(StudyAspectMixin, UpdateView):
    model = Publication
    form_class = PublicationForm


class PublicationDeleteView(StudyAspectMixin, DeleteView):
    model = Publication

study_registration/publications/templates/publications/_study_detail_publications.html
{% load i18n %}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center">
        <h2 class="m-0">{% translate 'Publications' %}</h2>
        {% if is_owner %}
            <div class="d-print-none flex-shrink-0 ms-1">
                <a href="{% url 'publications:create' study.pk study.short_title %}" class="btn btn-sm btn-primary">{% translate 'Add publication' %}</a>
            </div>
        {% endif %}
    </div>
    <div class="card-body">
        <ul class="mb-0 p-0">
            {% for publication in study.publication_set.all %}
                <li class="d-block mb-3">
                    {% if is_owner %}
                        <div class="d-print-none float-end ms-1 mb-1">
                            <a href="{% url 'publications:update' study.pk study.short_title publication.pk %}" class="btn btn-sm btn-outline-primary">{% translate 'Update' %}</a>
                            <a href="{% url 'publications:delete' study.pk study.short_title publication.pk %}" class="btn btn-sm btn-outline-danger">{% translate 'Delete' %}</a>
                        </div>
                    {% endif %}
                    {{ publication.text|urlize }}
                </li>
            {% empty %}
                <li class="d-block alert alert-warning">{% translate 'No publications so far' %}</li>
            {% endfor %}
        </ul>
    </div>
</div>

study_registration/publications/templates/publications/publication_base.html
{% extends "studies/study_base.html" %}
{% load i18n %}

{% block title %}
    {% if publication %}
        {{ publication }}
    {% else %}
        {% translate "Add publication" %}
    {% endif %}
    &middot; {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    {% if publication %}
        <li class="breadcrumb-item"><a href="{% url 'publications:update' study.pk study.short_title publication.pk %}">{{ publication }}</a></li>
    {% else %}
        <li class="breadcrumb-item"><a href="{% url 'publications:create' study.pk study.short_title %}">{% translate 'Add publication' %}</a></li>
    {% endif %}
{% endblock %}

study_registration/publications/templates/publications/publication_confirm_delete.html
{% extends "publications/publication_base.html" %}
{% load i18n %}

{% block title %}{% translate 'Delete' %} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'publications:delete' study.pk study.short_title publication.pk %}">{% translate 'Delete' %}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktranslate with title=object.title %}
                Are you sure you want to <strong>permanently delete</strong> the publication "{{ title }}"?
            {% endblocktranslate %}
        </p>
        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}

study_registration/publications/templates/publications/publication_form.html
{% extends "publications/publication_base.html" %}
{% load i18n static django_bootstrap5 %}

{% block content %}
    <form method="post">
        {% include 'form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.doi %}
        {% bootstrap_field form.title %}
        {% bootstrap_field form.authors %}
        {% bootstrap_field form.journal %}
        {% bootstrap_field form.year %}

        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

{% block extra_scripts %}
    <script type="module" src="{% static 'semantic-scholar.js' %}"></script>
{% endblock %}

{% block extra_connect %}https://api.semanticscholar.org{% endblock %}