study_registration/studies/urls.py
from django.urls import path

from .api import StudyJSONView
from .api import StudyMarcXMLView
from .views import CalendarView
from .views import EthicsConfirmView
from .views import MyStudiesView
from .views import StaffDataUpdateView
from .views import StorageCreateView
from .views import StudyArchiveTxtView
from .views import StudyCreateView
from .views import StudyDeleteView
from .views import StudyDetailView
from .views import StudyListView
from .views import StudyMaintenanceView
from .views import StudyRedirectView
from .views import StudyUpdateView

app_name = 'studies'
urlpatterns = [
    path('', StudyListView.as_view(), name='list'),
    path('mine/', MyStudiesView.as_view(), name='mine'),
    path('new/', StudyCreateView.as_view(), name='create'),
    path('calendar/', CalendarView.as_view(), name='calendar'),
    path('calendar/<int:year>-<int:month>/', CalendarView.as_view(), name='calendar'),
    path('<int:pk>/', StudyRedirectView.as_view()),
    path('<int:pk>-<slug:slug>/', StudyDetailView.as_view(), name='detail'),
    path('<int:pk>-<slug:slug>.json', StudyJSONView.as_view(), name='api'),
    path('<int:pk>-<slug:slug>.mrcx', StudyMarcXMLView.as_view(), name='marc-xml'),
    path('<int:pk>-<slug:slug>/update/', StudyUpdateView.as_view(), name='update'),
    path('<int:pk>-<slug:slug>/delete/', StudyDeleteView.as_view(), name='delete'),
    path('<int:pk>-<slug:slug>/storage/', StorageCreateView.as_view(), name='storage'),
    path('<int:pk>-<slug:slug>/archive.txt', StudyArchiveTxtView.as_view()),
    path('<int:pk>-<slug:slug>/ethics/', EthicsConfirmView.as_view(), name='ethics'),
    path('<int:pk>-<slug:slug>/staff/', StaffDataUpdateView.as_view(), name='staff'),
    path('maintenance/', StudyMaintenanceView.as_view(), name='maintenance'),
]

study_registration/urls.py
from bootstrap_colors.views import BootstrapColorsView
from django.contrib import admin
from django.contrib.auth.views import LoginView
from django.contrib.auth.views import LogoutView
from django.urls import include
from django.urls import path
from django.views.decorators.cache import cache_control
from django.views.generic import RedirectView
from django.views.generic import TemplateView

from study_registration.budgets.views import BudgetListView
from study_registration.deployments.api import DeploymentsApiView
from study_registration.deployments.views import DeploymentListView

urlpatterns = [
    path('', RedirectView.as_view(pattern_name='studies:list'), name='index'),
    path('about/', TemplateView.as_view(template_name='about.html'), name='about'),
    path(
        'contact/', TemplateView.as_view(template_name='contact.html'), name='contact'
    ),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('admin/', admin.site.urls),
    path('colors.css', cache_control(max_age=86400)(
        BootstrapColorsView.as_view()
    ), name='colors'),
    path(
        'studies/<int:study_pk>-<slug:study_short>/publications/',
        include('study_registration.publications.urls', namespace='publications'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/datasets/',
        include('study_registration.datasets.urls', namespace='datasets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/budgets/',
        include('study_registration.budgets.urls', namespace='budgets'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/deployments/',
        include('study_registration.deployments.urls', namespace='deployments'),
    ),
    path(
        'studies/<int:study_pk>-<slug:study_short>/biosamples/',
        include('study_registration.biosamples.urls', namespace='biosamples'),
    ),
    path('studies/', include('study_registration.studies.urls', namespace='studies')),
    path('budgets/', BudgetListView.as_view(), name='budget-list'),
    path('deployments/', DeploymentListView.as_view(), name='deployment-list'),
    path('api/deployments/', DeploymentsApiView.as_view(), name='deployment-api'),
]

try:
    import debug_toolbar

    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]
except ImportError:
    pass

study_registration/studies/models.py
import datetime
import re
from urllib.parse import urlencode

from django.conf import settings
from django.core import validators
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _

from study_registration.utils.fields import DateField


class Status(models.Model):
    name = models.CharField(_('Name'), max_length=254, unique=True)
    color = models.CharField(_('Color'), max_length=32, choices=[
        ('primary', _('primary')),
        ('secondary', _('secondary')),
        ('success', _('success')),
        ('danger', _('danger')),
        ('warning', _('warning')),
        ('info', _('info')),
        ('light', _('light')),
        ('dark', _('dark')),
    ])

    def __str__(self):
        return self.name


class Department(models.Model):
    name = models.CharField(_('Name'), max_length=254, unique=True)
    ldap_department = models.CharField(_('LDAP department'), max_length=254, blank=True)
    enable_budgets = models.BooleanField(_('Enable budgets'), default=False)
    is_active = models.BooleanField(_('active'), default=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name

    @cached_property
    def enable_deployments(self):
        return self.deploytarget_set.exists()


class Project(models.Model):
    created_at = models.DateField(_('Created at'), auto_now_add=True)
    title = models.CharField(_('Title'), max_length=255, unique=True)

    class Meta:
        ordering = ['title']

    def __str__(self):
        return self.title


class EthicsBoard(models.Model):
    name = models.CharField(_('Name'), max_length=254, unique=True)

    class Meta:
        ordering = ['name']

    def __str__(self):
        return self.name


class StudyQuerySet(models.QuerySet):
    def get_by_key(self, key):
        m = re.match('([0-9]+)-([-a-zA-Z0-9_]+)', key)
        if not m:
            raise Study.DoesNotExist
        return self.get(pk=int(m[1], 10), short_title=m[2])


class Study(models.Model):
    created_at = models.DateField(_('Created at'), auto_now_add=True)
    updated_at = models.DateField(_('Updated at'), auto_now=True)
    imported_from = models.CharField(
        _('Imported from'),
        max_length=254,
        blank=True,
        help_text=_(
            'If anything is entered here, users will not be asked if '
            'they want to create a storage folder'
        ),
    )
    owners = models.ManyToManyField(
        settings.AUTH_USER_MODEL,
        limit_choices_to={'is_active': True},
        verbose_name=_(
            'Users who can edit this study profile and access the private folder'
        ),
    )

    title = models.CharField(_('Title'), max_length=254)
    short_title = models.CharField(
        _('Short title'),
        help_text=_(
            'The short title will be used to refer to this study within '
            'the institute context, e.g., to create a physical folder '
            'on the server. Therefore, only use lower-case letters, numbers, '
            'or hyphens.'
        ),
        max_length=254,
        validators=[
            validators.RegexValidator(
                r'^[-a-z0-9]+\Z',
                _('Only use lower-case letters, numbers, and hyphens.')
            ),
            validators.MaxLengthValidator(16),
        ],
    )
    aliases = models.CharField(
        _('Other titles or acronyms'),
        help_text=_(
            'Please compile a complete list of additional titles that '
            'may refer to your study, including e.g. a German title '
            'used in communication with participants.'
        ),
        max_length=254,
        blank=True,
    )
    end = DateField(
        _('Expected end of study'),
        help_text=_(
            'When analyses are completed, manuscripts are submitted, and the data is '
            'no longer in active use, it should be moved to an archive in order to '
            'free up storage capacity. Entering this date allows the Rasearch Data '
            'Management Team to contact you to coordinate the archiving process.'
        ),
        blank=True,
        null=True,
    )
    description = models.TextField(
        _('Description'),
        help_text=_(
            'This text should allow other researchers to quickly grasp whether this '
            'study and the related data could be of interest to them.'
        ),
        blank=True,
    )
    department = models.ForeignKey(
        Department, verbose_name=_('Department'), on_delete=models.CASCADE
    )
    project = models.ForeignKey(
        Project,
        verbose_name=_('Project'),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    contact_person = models.ForeignKey(
        settings.AUTH_USER_MODEL,
        verbose_name=_('Contact person'),
        help_text=_(
            'The contact person must be reachable. Before the current contact person '
            'leaves the institute, they must pass on the study to someone else.'
        ),
        on_delete=models.PROTECT,
        limit_choices_to={
            'is_active': True,
        },
        related_name='+',
    )
    affiliated_scientists = models.CharField(
        _('Affiliated scientists'),
        max_length=254,
        help_text=_(
            'You can use the same format as you would use for the authors of a paper.'
        ),
    )

    ethics_board = models.ForeignKey(
        EthicsBoard,
        verbose_name=_('Ethics board'),
        help_text=_(
            'Please remember to save the application and approval to the study folder.'
        ),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )
    ethics_confirmed = models.DateField(
        _('Ethics vote confirmed'), blank=True, null=True
    )

    storage_location = models.CharField(
        _('Storage location'), max_length=255, blank=True, null=True, unique=True
    )
    storage_archived = models.DateField(_('Storage archived'), blank=True, null=True)
    storage_archive_name = models.CharField(
        _('Storage archive name'), max_length=255, blank=True
    )
    storage_deleted = models.DateField(
        _('Storage deleted'),
        help_text=_(
            'The data is no longer available, neither from the storage '
            'location nor the archive.'
        ),
        blank=True,
        null=True,
    )
    ldap_group_managed = models.BooleanField(
        _('LDAP group is managed'),
        help_text=_(
            'If selected, access permissions for the storage location will '
            'automatically be updated when owners change.'
        ),
        default=False,
    )
    ldap_group_synced = models.BooleanField(_('LDAP group is synced'), default=False)

    staff_followup = DateField(_('Follow-Up'), blank=True, null=True)
    staff_status = models.ForeignKey(
        Status,
        verbose_name=_('Status'),
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
    )

    objects = StudyQuerySet.as_manager()

    def get_storage_archive_name(self):
        if self.storage_archive_name:
            return self.storage_archive_name
        elif self.storage_archived:
            year = self.storage_archived.year
            quarter = ((self.storage_archived.month - 1) // 3) + 1
            return f'ArchivSRT_{year}-Q{quarter}'

    class Meta:
        ordering = ['-pk']
        permissions = [
            ('view_storage', _('Can view storage')),
        ]

    def __str__(self):
        return f'{self.pk}-{self.short_title}'

    def get_absolute_url(self):
        return reverse(
            'studies:detail', kwargs={'pk': self.pk, 'slug': self.short_title}
        )

    def data_reused_by(self):
        return Study.objects.filter(dataset__reuse_study=self).distinct().order_by('pk')

    @property
    def storage_is_archived(self):
        today = datetime.date.today()
        return self.storage_archived and self.storage_archived < today

    @property
    def storage_is_deleted(self):
        today = datetime.date.today()
        return self.storage_deleted and self.storage_deleted < today

    @property
    def storage_request_url(self):
        if not settings.CREATE_TICKET_URL:
            return None
        return settings.CREATE_TICKET_URL + '?' + urlencode({
            'summary': f'[Quota] Request to increase Isilon quota for study {self}',
            'description': (
                '[Please describe how much storage space you need and why you need it.]'
            ),
        })


class Keyword(models.Model):
    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    name = models.CharField(_('Name'), max_length=128)

    class Meta:
        unique_together = [['study', 'name']]

    def __str__(self):
        return self.name


class Link(models.Model):
    WEBSITE = 1
    PREREG = 2
    DATA = 3
    CODE = 4

    study = models.ForeignKey(Study, on_delete=models.CASCADE)
    url = models.URLField(_('URL'))
    type = models.SmallIntegerField(_('Type'), choices=[
        (WEBSITE, _('Website')),
        (PREREG, _('Preregistration')),
        (DATA, _('Public data repository')),
        (CODE, _('Public code repository')),
    ])

    class Meta:
        ordering = ['type', 'pk']

study_registration/users/models.py
from django.contrib.auth.models import AbstractUser
from django.contrib.auth.models import UserManager as _UserManager
from django.db import models
from django.utils.translation import gettext_lazy as _

from study_registration.studies.models import Department


class UserManager(_UserManager):
    def with_perm(self, perm, *args, **kwargs):
        backend = 'django.contrib.auth.backends.ModelBackend'
        return super().with_perm(perm, *args, backend=backend, **kwargs)


class User(AbstractUser):
    default_department = models.ForeignKey(
        Department,
        verbose_name=_('Default department'),
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
    )

    phone = models.CharField(max_length=64, blank=True)
    office = models.CharField(max_length=64, blank=True)

    objects = UserManager()

    def get_full_name(self):
        return super().get_full_name() or self.get_username()

    def __str__(self):
        if self.email:
            return f'{self.get_full_name()} <{self.email}>'
        else:
            return self.get_full_name()

study_registration/studies/forms.py
from django import forms
from django.db import models
from django.utils.translation import gettext_lazy as _

from study_registration.utils.forms import TagField

from .models import Department
from .models import Keyword
from .models import Study


class StudyUpdateForm(forms.ModelForm):
    keywords = TagField(
        label=_('Keywords'),
        help_text=_(
            "Describe your study's research topic, the data type "
            'acquired, methods used, etc. These keywords allow '
            'other researchers to find your study and get in '
            'touch if they are working on related topics. You can '
            'select keywords that have been used before from the auto-'
            'completion. If none of the existing keywords sound right, '
            'you can also create a new keyword by hitting enter. '
            'Please carefully check for existing synonyms before '
            'creating a new keyword.'
        ),
        initial=[],
        required=False,
    )

    class Meta:
        model = Study
        fields = [
            'title',
            'aliases',
            'end',
            'contact_person',
            'department',
            'project',
            'affiliated_scientists',
            'owners',
            'ethics_board',
            'description',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        for key in ['contact_person', 'owners']:
            self.fields[key].empty_label = ''
            self.fields[key].widget.attrs.update({
                'data-select': True,
                'data-select-input-class': 'form-control',
                'data-select-value-class': 'badge text-bg-secondary badge-delete',
            })

        self.fields['department'].queryset = Department.objects.filter(
            models.Q(is_active=True) | models.Q(pk=self.instance.department_id)
        )

        self.fields['keywords'].choices = [
            (s, s) for s in (
                Keyword.objects
                .values_list('name', flat=True)
                .alias(count=models.Count('name'))
                .order_by('-count')
                .distinct()
            )
        ]

        if self.instance.pk:
            self.fields['keywords'].initial = list(
                self.instance.keyword_set.values_list('name', flat=True)
            )

    def save(self, *args, **kwargs):
        obj = super().save(*args, **kwargs)

        for keyword in obj.keyword_set.all():
            if keyword.name not in self.cleaned_data['keywords']:
                keyword.delete()
        for name in self.cleaned_data['keywords']:
            obj.keyword_set.get_or_create(name=name)

        return obj


class StudyCreateForm(StudyUpdateForm):
    class Meta:
        model = Study
        fields = [
            *StudyUpdateForm.Meta.fields,
            'short_title',
        ]
        labels = {
            'short_title': _('Short title (cannot be changed later)')
        }

study_registration/studies/templates/studies/_study_detail_general.html
{% load i18n static utils %}

<div class="card">
    <div class="card-header d-flex justify-content-between align-items-center position-relative">
        <h1 class="h2 m-0">{{ study.title }}</h1>
        {% if is_owner %}
            <div class="d-print-none flex-shrink-0 ms-1">
                <a href="{% url 'studies:update' study.pk study.short_title %}" class="btn btn-sm btn-primary">{% translate 'Update' %}</a>
                <a href="{% url 'studies:delete' study.pk study.short_title %}" class="btn btn-sm btn-danger">{% translate 'Delete study' %}</a>
            </div>
        {% endif %}
    </div>
    <div class="card-body">
        <div class="row g-5">
            <div class="col-md-8">
                <div class="mb-2">
                    {{ study|display:'affiliated_scientists' }}
                    {% if study.project %}
                        &middot; {{ study|display:'project' }}
                    {% endif %}
                    &middot; {{ study|display:'department' }}
                </div>
                {% if study.description %}
                    {{ study|display:'description'|linebreaks|urlize }}
                {% else %}
                    <p><em>{% translate 'No description yet' %}</em></p>
                {% endif %}
                <ul class="p-0">
                    {% for keyword in study.keyword_set.all %}
                        <li class="d-inline-block">
                            <a href="{% url 'studies:list' %}?keyword={{ keyword.name|iriencode }}" class="badge text-bg-light border text-decoration-none" rel="tag">{{ keyword }}</a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="col-md-4">
                <dl class="mb-0">
                    <dt>{% translate 'Study ID' %}</dt>
                    <dd>{{ study }}</dd>

                    <dt class="mt-3">{{ study|verbose_name:'created_at' }}</dt>
                    <dd>{{ study|display:'created_at' }}</dd>

                    {% if study.end %}
                        <dt class="mt-3">{{ study|verbose_name:'end' }}</dt>
                        <dd>{{ study|display:'end' }}</dd>
                    {% endif %}

                    {% if study.aliases %}
                        <dt class="mt-3">{{ study|verbose_name:'aliases' }}</dt>
                        <dd>{{ study|display:'aliases' }}</dd>
                    {% endif %}

                    <dt class="mt-3">{{ study|verbose_name:'contact_person' }}</dt>
                    <dd>
                        <a {% if study.contact_person.email %}href="mailto:{{ study.contact_person.email }}"{% endif %}>{{ study.contact_person.get_full_name }}</a>
                    </dd>

                    {% if study.storage_is_deleted %}
                        <dt class="mt-3">{{ study|verbose_name:'storage_location' }}</dt>
                        <dd class="text-secondary">{% translate 'deleted' %}</dd>
                    {% elif study.storage_is_archived %}
                        <dt class="mt-3">{{ study|verbose_name:'storage_location' }}</dt>
                        <dd class="text-secondary">
                            {% blocktranslate with name=study.get_storage_archive_name %}archived as "{{ name }}"{% endblocktranslate %}
                        </dd>
                    {% elif study.storage_location %}
                        <dt class="mt-3">{{ study|verbose_name:'storage_location' }}</dt>
                        <dd>
                            {% smb_url_or_unc study.storage_location %}
                            {% if quota %}
                                <label class="d-block text-end lh-1 my-1">
                                    <meter class="w-100" value="{{ quota.usage }}" optimum="0" low="{% widthratio quota.quota 100 75 %}" high="{% widthratio quota.quota 100 90 %}" max="{{ quota.quota }}"></meter>
                                    {{ quota.usage|format_bytes }} / {{ quota.quota|format_bytes }}
                                </label>
                                {% if study.storage_request_url %}
                                    <a class="btn btn-sm btn-outline-primary" href="{{ study.storage_request_url }}" target="_blank" referrerpolicy="same-origin">{% translate "Request more storage" %}</a>
                                {% endif %}
                            {% endif %}
                        </dd>
                    {% elif is_owner and not study.imported_from %}
                        <dt class="mt-3">{{ study|verbose_name:'storage_location' }}</dt>
                        <dd><a href="{% url 'studies:storage' study.pk study.short_title %}" class="btn btn-outline-primary btn-sm">{% translate 'Create' %}</a></dd>
                    {% endif %}

                    <dt class="mt-3">{{ study|verbose_name:'ethics_board' }}</dt>
                    <dd>
                        {{ study|display:'ethics_board' }}
                        {% if study.ethics_confirmed %}
                            {% icon 'circle-check' label=_('Confirmed') %}
                        {% else %}
                            {% if is_owner %}
                                {% icon 'circle-exclamation text-danger animation-attention' label=_('Attention!') %}
                                <p class="form-text">{% translate 'Once you receive the ethics approval, please save the application and approval to the ethics folder at your storage location and inform us (<a href="mailto:rdm@mpib-berlin.mpg.de">rdm@mpib-berlin.mpg.de</a>). We will then confirm that your study has ethical approval.' %}</p>
                            {% endif %}
                            {% if user.is_superuser %}
                                <form method="POST" action="{% url 'studies:ethics' study.pk study.short_title %}">
                                    {% csrf_token %}
                                    <button class="btn btn-sm btn-outline-primary">{% translate 'Confirm' %}</button>
                                </form>
                            {% endif %}
                        {% endif %}
                    </dd>

                    {% if study.link_set.exists %}
                        <dt class="mt-3">{% translate 'Study links' %}</dt>
                        {% for link in study.link_set.all %}
                            <dd class="icon-list {% if not forloop.last %}mb-0{% endif %}">
                                <a href="{{ link.url }}" class="text-decoration-none">
                                    {% if link.type == link.WEBSITE %}
                                        {% icon 'home' %}
                                    {% elif link.type == link.PREREG %}
                                        <i class="fa"><img src="{% static 'open-science-badges/preregistered.svg'%}" alt="" class="img-icon"></i>
                                    {% elif link.type == link.DATA %}
                                        <i class="fa"><img src="{% static 'open-science-badges/open-data.svg'%}" alt="" class="img-icon"></i>
                                    {% elif link.type == link.CODE %}
                                        <i class="fa"><img src="{% static 'open-science-badges/open-materials.svg'%}" alt="" class="img-icon"></i>
                                    {% endif %}
                                    <span class="text-decoration-underline">{{ link|display:'type' }}</span>
                                </a>
                            </dd>
                        {% endfor %}
                    {% endif %}

                    {% if study.data_reused_by.exists %}
                        <dt class="mt-3">{% translate 'Data reused by' %}</dt>
                        {% for other in study.data_reused_by %}
                            <dd class="icon-list {% if not forloop.last %}mb-0{% endif %}">
                                <a href="{{ other.get_absolute_url }}" class="text-decoration-none">
                                    <i class="fa"><img src="{% static 'reuse.svg'%}" alt="" class="img-icon"></i>
                                    <span class="text-decoration-underline">{{ other }}</span>
                                </a>
                            </dd>
                        {% endfor %}
                    {% endif %}

                    {% if user.is_staff %}
                        <dt class="mt-3">{% translate 'Follow-up' %}</dt>
                            <div class="mb-1">
                                <time>{{ study.staff_followup|date|default:'—' }}</time>
                                {% if study.staff_status %}
                                    <span class="badge text-bg-{{ study.staff_status.color }}">{{ study.staff_status.name }}</span>
                                {% endif %}
                            </div>
                            <a class="btn btn-sm btn-outline-primary" href="{% url 'studies:staff' study.pk study.short_title %}">{% translate 'Edit' %}</a>
                        </dt>
                    {% endif %}
                </dl>
            </div>
        </div>
    </div>
</div>

study_registration/studies/templates/studies/calendar.html
{% extends "studies/study_base.html" %}
{% load i18n %}

{% block content %}
    <ul>
        {% for date, study, type, color in items %}
            <li>{{ date }}: <a href="{{ study.get_absolute_url }}">{{ study }}</a> <span class="badge text-bg-{{ color }}">{{ type }}</span></li>
        {% empty %}
            <li><em>{% translate 'No events' %}</em></li>
        {% endfor %}
    </ul>

    <nav class="d-flex justify-content-between mb-3" aria-label="{% translate 'Months' %}">
        {% if month > 1 %}
            <a class="btn btn-secondary" href="{% url 'studies:calendar' year month|add:'-1' %}">{% translate 'Previous month' %}</a>
        {% else %}
            <a class="btn btn-secondary" href="{% url 'studies:calendar' year|add:'-1' 12 %}">{% translate 'Previous month' %}</a>
        {% endif %}

        {% if month < 12 %}
            <a class="btn btn-secondary" href="{% url 'studies:calendar' year month|add:'1' %}">{% translate 'Next month' %}</a>
        {% else %}
            <a class="btn btn-secondary" href="{% url 'studies:calendar' year|add:'1' 1 %}">{% translate 'Next month' %}</a>
        {% endif %}
    </nav>
{% endblock %}

study_registration/studies/templates/studies/staff_data_form.html
{% extends "studies/study_base.html" %}
{% load i18n static django_bootstrap5 utils %}

{% block title %}
    {% translate "Staff Data" %} &middot; {{ block.super }}
{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'studies:update' study.pk study.short_title %}">{% translate 'Staff Data' %}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% include 'form_errors.html' with form=form %}
        {% csrf_token %}

        {% bootstrap_field form.staff_status %}
        {% bootstrap_field form.staff_followup %}

        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-primary">{% translate 'Save' %}</button>
        </div>
    </form>
{% endblock %}

study_registration/studies/templates/studies/storage_create.html
{% extends "studies/study_base.html" %}
{% load static i18n utils %}

{% block title %}{% translate "Creating study folder" %} &middot; {{ block.super }}{% endblock %}

{% block content %}
    <h2>{% translate 'Creating study folder' %}</h2>
    {% if study.storage_is_deleted %}
        <p class="alert alert-info">{% translate 'Folder is already deleted' %}</p>
    {% elif study.storage_is_archived %}
        <p class="alert alert-info">{% translate 'Folder is already archived' %}</p>
    {% elif study.storage_location %}
        <p class="alert alert-info">{% translate 'Folder already exists:' %} {% smb_url_or_unc study.storage_location %}</p>
    {% else %}
        <p>{% translate 'This may take some time.' %}</p>
        <form method="POST" class="d-grid">
            {% csrf_token %}
            <svg class="progress w-100 mb-3" viewbox="0 0 100 20" preserveAspectRatio="none" hidden>
                <rect id="progress" class="text-primary" fill="currentColor" width="0" height="20" />
            </svg>
            <button class="btn btn-primary btn-lg" id="fallback">{% translate 'Create folder' %}</button>
        </form>
        <script type="module" src="{% static 'storage.js' %}"></script>
    {% endif %}
{% endblock %}

study_registration/studies/templates/studies/study_base.html
{% extends "base.html" %}
{% load i18n %}

{% block title %}{% if study %}{{ study }} &middot; {% endif %}{{ block.super }}{% endblock %}

study_registration/studies/templates/studies/study_confirm_delete.html
{% extends "studies/study_base.html" %}
{% load i18n %}

{% block title %}{% translate "Delete" %} &middot; {{ block.super }}{% endblock %}

{% block breadcrumbs %}
    {{ block.super }}
    <li class="breadcrumb-item"><a href="{% url 'studies:delete' study.pk study.short_title %}">{% translate 'Delete' %}</a></li>
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <p>
            {% blocktranslate with title=study.title %}
                Are you sure you want to <strong>permanently delete</strong> the study "{{ title }}"?
            {% endblocktranslate %}
        </p>
        <div class="d-print-none mb-3">
            <a href="{{ study.get_absolute_url }}" class="btn btn-outline-primary">{% translate 'Cancel' %}</a>
            <button class="btn btn-danger">{% translate 'Confirm' %}</button>
        </div>
    </form>
{% endblock %}